% I_display function
% This function creates all handle objects

% Input:    h       handle for all objects

% Output:   h       handle for all objects

function [h,c] = YR_display(h,c)

% check that no other figures are open in matlab, close them if needed

% Set basic colors

c.background    = [1 1 1];      %white
c.foreground    = [1 1 1];      %white
c.linecolor     = [0 .62 1];    %lightblue
c.textcolor     = [0 0 0];      %black
c.greenl        = [.8 1 .8];    %green (for buttons)
c.greend        = [0 .5 0];     %green (for text)
c.orange        = [.8500 .3250 .0980]; % orange for selected trace
c.blue          = [0 .4470 .7410];
% Create main figure + assign properties
h.mainFig = figure('menubar',       'none',...
    'color',         c.background,...
    'name',          'SimplYRead',...
    'numbertitle',   'off',...
    'units',         'normalized',...
    'outerposition', [0.01 .05 0.98 0.95]);
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% UI MENU

h.menu.option = uimenu('parent',             h.mainFig,...
    'label',              'Options');

h.menu.typeFile = uimenu(h.menu.option, 'label', 'Type of file saved');

h.menu.plannedRecord = uimenu(h.menu.option, 'label', 'Recording schedule');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PANEL FILENAME

% Panel for creating the folder where all files of the experiment will be
% saved

h.panelFile = uipanel('parent',             h.mainFig,...
    'backgroundcolor',    c.background,...
    'units',              'normalized',...
    'position',           [0.02 0.9 0.20 0.08],...
    'title',              'Create File');

h.pF_edit = uicontrol('style',              'edit',...
    'parent',             h.panelFile,...
    'units',              'normalized',...
    'position',           [0.01 0.6 0.78 0.35],...
    'backgroundcolor',    c.background,...
    'string',             'Browse for folder -->',...
    'enable',             'inactive');

h.pF_browse = uicontrol('style',            'pushbutton',...
    'parent',           h.panelFile,...
    'units',            'normalized',...
    'position',         [0.8 0.6 0.19 0.35],...
    'string',           '...',...
    'backgroundcolor',  c.background);

h.pF_text = uicontrol('style',              'text',...
    'parent',             h.panelFile,...
    'units',              'normalized',...
    'position',           [.01 .1 .2 .3],...
    'backgroundcolor',    c.background,...
    'string',             'File Name:',...
    'horizontalalignment','right');

h.pF_editFileName = uicontrol('style',              'edit',...
    'parent',              h.panelFile,...
    'units',              'normalized',...
    'position',           [.25 .1 .54 .35],...
    'string',             'DATE_',...
    'backgroundcolor',    c.background);

h.pF_okButton = uicontrol('style',          'pushbutton',...
    'parent',         h.panelFile,...
    'units',          'normalized',...
    'position',       [0.8 0.1 0.19 0.35],...
    'string',         '-Ok-',...
    'backgroundcolor',c.background);

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PANEL PARAMETERS

h.panelPars = uipanel('parent',             h.mainFig,...
    'backgroundcolor',    c.background,...
    'units',              'normalized',...
    'position',           [0.02 0.50 0.20 0.39],...
    'title',              'Set Parameters');

h.setSFtxt = uicontrol('style',             'text',...
    'parent',            h.panelPars,...
    'backgroundcolor',   c.background,... %c.background
    'units',             'normalized',...
    'position',          [.02 .88 .46 .05],...
    'string',            'Sampling frequency:',...
    'horizontalalignment','right');

h.setSF = uicontrol('style',                'popup',...
    'parent',               h.panelPars,...
    'units',                'normalized',...
    'position',             [.52 .9 .46 .05],...
    'string',               'frequencies',...
    'Enable',               'off');

h.setLayouttxt = uicontrol('style',         'text',...
    'parent',        h.panelPars,...
    'backgroundcolor',c.background,... %c.background
    'units',         'normalized',...
    'position',      [.02 .78 .46 .05],...
    'string',        'Display Layout:',...
    'horizontalalignment', 'right');

h.setLayout = uicontrol('style',             'popup',...
    'parent',           h.panelPars,...
    'units',            'normalized',...
    'position',         [.52 .8 .46 .05],...
    'string',           '8x1',...
    'Enable',           'off');

h.butStart = uicontrol('style',             'pushbutton',...
    'parent',            h.panelPars,...
    'backgroundcolor',   c.background',...
    'units',             'normalized',...
    'position',          [.02 .02 .46 .08],...
    'string',            'Start',...
    'Enable',            'off');

h.butStop = uicontrol('style',              'pushbutton',...
    'parent',             h.panelPars,...
    'backgroundcolor',    c.background,...
    'units',              'normalized',...
    'position',           [.52 .02 .46 .08],...
    'string',             'Stop',...
    'Enable',             'off');

h.butNoiseOn = uicontrol('style',              'pushbutton',...
    'parent',             h.panelPars,...
    'backgroundcolor',    c.background,...
    'units',              'normalized',...
    'position',           [.02 .12 .46 .08],...
    'string',             'Play Noise Protocol',...
    'Enable',             'off');

h.butNoiseOff = uicontrol('style',              'pushbutton',...
    'parent',             h.panelPars,...
    'backgroundcolor',    c.background,...
    'units',              'normalized',...
    'position',           [.52 .12 .46 .08],...
    'string',             'Stop Noise Protocol',...
    'Enable',             'off');

% Panel set gain
h.panelGain = uipanel('parent',             h.panelPars,...
    'units',              'normalized',...
    'position',           [.02 .55 .96 .17],...
    'title',              'Set Trace Gain',...
    'backgroundcolor',    c.background,...
    'visible',            'off');

h.gainPlus = uicontrol('Style',             'pushbutton',...
    'parent',            h.panelGain,...
    'units',             'normalized',...
    'position',          [.05 .15 .4 .7],...
    'string',            '+',...
    'fontsize',          12,...
    'backgroundcolor',   c.background);

h.gainMinus = uicontrol('Style',            'pushbutton',...
    'parent',            h.panelGain,...
    'units',             'normalized',...
    'position',          [.55 .15 .4 .7],...
    'string',            '-',...
    'fontsize',          12,...
    'backgroundcolor',   c.background);


h.setNotchtxt = uicontrol('style',         'text',...
    'parent',        h.panelPars,...
    'backgroundcolor',c.background,... %c.background
    'units',         'normalized',...
    'position',      [.02 .45 .46 .05],...
    'string',        'Apply Notch:',...
    'horizontalalignment', 'right');

h.setNotch = uicontrol('style',             'popup',...
    'parent',           h.panelPars,...
    'units',            'normalized',...
    'position',         [.52 .47 .46 .05],...
    'string',           'Nope',...
    'Enable',           'off');
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PANEL REC INFO

h.panelRecInfo = uipanel('parent',          h.mainFig,...
    'backgroundcolor', c.background,...
    'units',           'normalized',...
    'position',        [0.02 0.37 0.2 0.12],...
    'title',           'Rec Info');

h.recStarttxt = uicontrol('style',          'text',...
    'parent',         h.panelRecInfo,...
    'backgroundcolor',c.background,...%c.background
    'units',          'normalized',...
    'position',       [.02 .55 .46 .25],...
    'string',         'Recording Start:',...
    'horizontalalignment', 'right');

h.recStartvalue = uicontrol('style',          'text',...
    'parent',         h.panelRecInfo,...
    'backgroundcolor',c.background,...%c.background
    'units',          'normalized',...
    'position',       [.52 .55 .46 .25],...
    'string',         'JUST NOW',...
    'horizontalalignment', 'center',...
    'fontweight',     'bold');

h.timeEltxt = uicontrol('style',          'text',...
    'parent',         h.panelRecInfo,...
    'backgroundcolor',c.background,...%c.background
    'units',          'normalized',...
    'position',       [.02 .1 .46 .25],...
    'string',         'Time Elapsed:',...
    'horizontalalignment', 'right');

h.timeElvalue = uicontrol('style',          'text',...
    'parent',         h.panelRecInfo,...
    'backgroundcolor',c.background,...%c.background
    'units',          'normalized',...
    'position',       [.52 .1 .46 .25],...
    'string',         'HH:MM:SS',...
    'horizontalalignment', 'center',...
    'fontweight',     'bold');


%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TAB GROUP FFT-VIDEO
h.tabgp = uitabgroup(h.mainFig,'Position',[0.02 0.02 0.2 0.34]);
h.panelFFT = uitab(h.tabgp,'Title','FFT','backgroundcolor', c.background);
h.tabVid = uitab(h.tabgp,'Title','Video','backgroundcolor', c.background);


%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PANEL TRACES
% The panel that contain the traces is now a tabgroup, created in YR_main
% under the function YR_createTabs

% h.panelTraces = uipanel('parent',           h.mainFig,...
%     'backgroundcolor',  c.background,...
%     'units',            'normalized',...
%     'position',         [.23 .02 .75 .96],...
%     'title',            'Traces');


h.fifo = uicontrol('style',              'text',...
    'parent',             h.mainFig,...
    'units',              'normalized',...
    'position',           [0.9 .005 .03 .015],...
    'backgroundcolor',    c.background,...
    'string',             'fifo');

%% Fill objects

% Get date of today and create beginning of filename
tempdate = [datestr(now,'yyyymmdd'),'_'];
h.pF_editFileName.String = tempdate;

% Set Layout options
layouts = {'Select Layout';'thals1';'iRo1';'Laura';'S1HL_opto';'8x1';'12x1';'9x1';'16x1';'RC_HeadChip';'SL_silicon16';'SL_AEPs';'SL_OAEPs';'EEG+Stim'; 'ALL';'10Pin';'DIO';'HUMAN';'EEG1';'LC-TRN_Pharm'};
h.setLayout.String = layouts;

frequencies = {'rate1000'; 'rate30000'};
h.setSF.String = frequencies;

notchFilters = {'Nope'; '50 Hz'};
h.setNotch.String = notchFilters;
end