function [ h ] = Y2R_mainFig( h )
%Y2R_MAINFIG creates the mianfig for yr2
fontna = 'Arial';

h.mainFig = figure('menubar', 'none',...
    'color',         'white',...
    'name',          'Symply2Read: v0.1; To record data with Intan.',...
    'numbertitle',   'off',...
    'units',         'normalized',...
    'outerposition', [.1 .1 .8 .8]);

h.filePanel = uipanel('parent', h.mainFig,...
    'FontName',           fontna,...
    'FontSize',           12,...
    'ForegroundColor',    'black',...
    'backgroundcolor',    'white',...
    'units',              'normalized',...
    'position',           [.05, .88, .9, .09],...
    'title',              'Settings');


h.browse = uicontrol('style', 'pushbutton',...
    'FontName', fontna,...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.05 .3 0.05 0.45],...
    'string',           '...',...
    'backgroundcolor',  'white');


h.fileEdit = uicontrol('style', 'edit',...
    'FontName', fontna,...
    'ForegroundColor', 'black',...
    'parent',             h.filePanel,...
    'units',              'normalized',...
    'position',           [0.12 .3 0.2 0.45],...
    'backgroundcolor',    'white',...
    'string',             [datestr(now,'yymmdd'),'_A1_A2_A3_A4_recordingName']);

h.recSettings = uicontrol('style', 'pushbutton',...
    'FontName', fontna,...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.34 .3 0.1 0.45],...
    'string',           'Recording settings',...
    'enable',           'off',...
    'backgroundcolor',  'white');

h.start = uicontrol('style', 'pushbutton',...
    'FontName', fontna,...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.46 .3 0.1 0.45],...
    'string',           'Start',...
    'enable',           'off',...
    'backgroundcolor',  'white');

h.console = uicontrol('parent', h.filePanel,...
    'FontName', 'Monospaced',...
    'ForegroundColor', 'black',...
    'style', 'text',...
    'fontsize',12,...
    'unit', 'normalized',...
    'position', [.58,.22,.4,.47],...
    'string', '>> Choose an output directory and name the file',...
    'horizontalalignment','left',...
    'backgroundcolor', 'white');

end

