classdef Adonis_recSettings < handle
    %Y2R_RECSETTINGS To ask for the configurations specifics
    
    properties
        
        display
        config
        startAt
        nFiles
        fileLength
        forground = 'black'
        background = [172/255, 207/255, 232/255];
        police = 'Century'
        cb1
        cb2
        cb3
        cb4
        contFrag
        
    end
    
    methods
        
        function obj = Adonis_recSettings(setfig, conf)
 
            settingPanel = uipanel('parent', setfig,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'backgroundcolor',    obj.background,...
                'units',              'normalized',...
                'position',           [0.05 0.05 0.9 0.9],...
                'title',              'Settings');
            
            %Read conf label
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.81,.45,.1],...
                'string', 'Read configuration : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            obj.display.config = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'popup',...
                'unit', 'normalized',...
                'position', [.52,.82,.4,.1],...
                'string', conf.confList,...
                'backgroundcolor', obj.background);
            
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.53,.75,.45,.1],...
                'string', 'A1          A2          A3          A4',...
                'horizontalalignment','left',...
                'backgroundcolor', obj.background);
            
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.725,.45,.1],...
                'string', 'Continuity : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.69,.45,.1],...
                'string', 'Fragility : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            % A1 set
            obj.cb1 = uibuttongroup('parent', settingPanel,...
                'unit', 'normalized',...
                'position', [.515,.757,.05,.065],...
                'backgroundcolor', obj.background);
            uicontrol(obj.cb1, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'position', [.11,.5,.9,.45],...
                'HandleVisibility','on',...
                'backgroundcolor', obj.background,...
                'userdata',1);
            uicontrol(obj.cb1, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'position', [.11,.001,.9,.45],...
                'HandleVisibility','on',...
                'backgroundcolor', obj.background,...
                'userdata',2);
            
            % A2 set
            obj.cb2 = uibuttongroup('parent', settingPanel,...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.615,.757,.05,.065]);
            uicontrol(obj.cb2, 'Style','radiobutton',...
                'String',' ',...
                'backgroundcolor', obj.background,...
                'unit', 'normalized',...
                'position', [.11,.5,.9,.45],...
                'HandleVisibility','on',...
                'userdata',1);
            uicontrol(obj.cb2, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.11,.001,.9,.45],...
                'HandleVisibility','on',...
                'userdata',2);
            
            % A3 set
            obj.cb3 = uibuttongroup('parent', settingPanel,...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.715,.757,.05,.065]);
            uicontrol(obj.cb3, 'Style','radiobutton',...
                'String',' ',...
                'backgroundcolor', obj.background,...
                'unit', 'normalized',...
                'position', [.11,.5,.9,.45],...
                'HandleVisibility','on',...
                'userdata',1);
            uicontrol(obj.cb3, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.11,.001,.9,.45],...
                'HandleVisibility','on',...
                'userdata',2);
            
            % A4 set
            obj.cb4 = uibuttongroup('parent', settingPanel,...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.815,.757,.05,.065]);
            uicontrol(obj.cb4, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.11,.5,.9,.45],...
                'HandleVisibility','on',...
                'userdata',1);
            uicontrol(obj.cb4, 'Style','radiobutton',...
                'String',' ',...
                'unit', 'normalized',...
                'backgroundcolor', obj.background,...
                'position', [.11,.001,.9,.45],...
                'HandleVisibility','on',...
                'userdata',2);
            
            %start at
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.6,.45,.1],...
                'string', 'Start at : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            nextday = datestr(addtodate(now,1,'day'));
            nextday = [nextday(1:12),'09:00:00'];
            
            obj.display.startAt = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.62,.4,.1],...
                'string', nextday,...
                'backgroundcolor', obj.background);
            
            %number of files
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.4,.45,.1],...
                'string', 'Number of files : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            obj.display.nFiles = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.42,.4,.1],...
                'string', '4',...
                'backgroundcolor', obj.background);
            
            %file length
            uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.2,.45,.1],...
                'string', 'File length (h) : ',...
                'horizontalalignment','right',...
                'backgroundcolor', obj.background);
            
            obj.display.fileLength = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.22,.4,.1],...
                'string', '12',...
                'backgroundcolor', obj.background);
            
            obj.display.ok1 = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'pushbutton',...
                'unit', 'normalized',...
                'string', 'Validate',...
                'Callback', @obj.validate,...
                'backgroundcolor', obj.background,...
                'position', [.2 .05 0.2 0.1]);
            
            obj.display.ok2 = uicontrol('parent', settingPanel,...
                'FontName', obj.police,...
                'ForegroundColor', obj.forground,...
                'style', 'pushbutton',...
                'unit', 'normalized',...
                'string', 'Start now',...
                'Callback', @obj.immediate,...
                'backgroundcolor', obj.background,...
                'position', [.6 .05 0.2 0.1]);
            
        end
        
        function validate(obj,~,~)
            obj.config = obj.display.config.Value;
            obj.startAt = obj.display.startAt.String;
            obj.nFiles = str2double(obj.display.nFiles.String);
            obj.fileLength = str2double(obj.display.fileLength.String);
            obj.contFrag = [obj.cb1.SelectedObject.UserData,...
                obj.cb2.SelectedObject.UserData,...
                obj.cb3.SelectedObject.UserData,...
                obj.cb4.SelectedObject.UserData];
            close('Settings')
        end
        
        function immediate(obj,~,~)
            obj.config = obj.display.config.Value;
            obj.startAt = 'now';
            obj.nFiles = str2double(obj.display.nFiles.String);
            obj.fileLength = str2double(obj.display.fileLength.String);
            obj.contFrag = [obj.cb1.SelectedObject.UserData,...
                obj.cb2.SelectedObject.UserData,...
                obj.cb3.SelectedObject.UserData,...
                obj.cb4.SelectedObject.UserData];
            close('Settings')
        end
      
        
    end
    
end

