function [ h ] = Adonis_mainFig( h )
%YPNOS_MAINFIG Summary of this function goes here
%   Detailed explanation goes here

bg = [172/255, 207/255, 232/255];

h.mainFig = figure('menubar', 'none',...
    'color',         bg,...
    'name',          'ADONIS: v0.1; Automatic Detection Of NREMS Infraslow State.',...
    'numbertitle',   'off',...
    'units',         'normalized',...
    'outerposition', [.1 .1 .8 .8]);

h.filePanel = uipanel('parent', h.mainFig,...
    'FontName',           'Century',...
    'FontSize',           12,...
    'ForegroundColor',    'black',...
    'backgroundcolor',    bg,...
    'units',              'normalized',...
    'position',           [.05, .88, .9, .09],...
    'title',              'Settings');


h.browse = uicontrol('style', 'pushbutton',...
    'FontName', 'Century',...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.05 .3 0.05 0.45],...
    'string',           '...',...
    'backgroundcolor',  bg);


h.fileEdit = uicontrol('style', 'edit',...
    'FontName', 'Century',...
    'ForegroundColor', 'black',...
    'parent',             h.filePanel,...
    'units',              'normalized',...
    'position',           [0.12 .3 0.2 0.45],...
    'backgroundcolor',    bg,...
    'string',             [datestr(now,'yymmdd'),'_']);

h.recSettings = uicontrol('style', 'pushbutton',...
    'FontName', 'Century',...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.34 .3 0.1 0.45],...
    'string',           'Recording settings',...
    'enable',           'off',...
    'backgroundcolor',  bg);

h.start = uicontrol('style', 'pushbutton',...
    'FontName', 'Century',...
    'ForegroundColor', 'black',...
    'parent',           h.filePanel,...
    'units',            'normalized',...
    'position',         [.46 .3 0.1 0.45],...
    'string',           'Start',...
    'enable',           'off',...
    'backgroundcolor',  bg);

h.console = uicontrol('parent', h.filePanel,...
    'FontName', 'Monospaced',...
    'ForegroundColor', 'black',...
    'style', 'text',...
    'fontsize',12,...
    'unit', 'normalized',...
    'position', [.58,.22,.4,.47],...
    'string', '>> Choose an output directory and name the file',...
    'horizontalalignment','left',...
    'backgroundcolor', bg);

end

