classdef Ypnos_recSettings < handle
    %YPNOS_RECSETTINGS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        
        display
        config
        startAt
        nFiles
        fileLength
        
    end
    
    methods
        
        function obj = Ypnos_recSettings(setfig, conf)
            
            settingPanel = uipanel('parent', setfig,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'backgroundcolor',    'black',...
                'units',              'normalized',...
                'position',           [0.05 0.05 0.9 0.9],...
                'title',              'Settings');
            
            %Read conf label
            uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.8,.45,.1],...
                'string', 'Read configuration : ',...
                'horizontalalignment','right',...
                'backgroundcolor', 'black');
            
            obj.display.config = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'popup',...
                'unit', 'normalized',...
                'position', [.52,.82,.4,.1],...
                'string', conf.confList,...
                'backgroundcolor', 'black');
            
            %start at
            uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.6,.45,.1],...
                'string', 'Start at : ',...
                'horizontalalignment','right',...
                'backgroundcolor', 'black');
            
            nextday = datestr(addtodate(now,1,'day'));
            nextday = [nextday(1:12),'09:00:00'];
            
            obj.display.startAt = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.62,.4,.1],...
                'string', nextday,...
                'backgroundcolor', 'black');
            
            %number of files
            uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.4,.45,.1],...
                'string', 'Number of files : ',...
                'horizontalalignment','right',...
                'backgroundcolor', 'black');
            
            obj.display.nFiles = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.42,.4,.1],...
                'string', '4',...
                'backgroundcolor', 'black');
            
            %file length
            uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'text',...
                'unit', 'normalized',...
                'position', [.04,.2,.45,.1],...
                'string', 'File length (h) : ',...
                'horizontalalignment','right',...
                'backgroundcolor', 'black');
            
            obj.display.fileLength = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'edit',...
                'unit', 'normalized',...
                'position', [.52,.22,.4,.1],...
                'string', '12',...
                'backgroundcolor', 'black');
            
            obj.display.ok1 = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'pushbutton',...
                'unit', 'normalized',...
                'string', 'Validate',...
                'Callback', @obj.validate,...
                'backgroundcolor', 'black',...
                'position', [.2 .05 0.2 0.1]);
            
            obj.display.ok2 = uicontrol('parent', settingPanel,...
                'FontName', 'Monospaced',...
                'ForegroundColor', 'white',...
                'style', 'pushbutton',...
                'unit', 'normalized',...
                'string', 'Start now',...
                'Callback', @obj.immediate,...
                'backgroundcolor', 'black',...
                'position', [.6 .05 0.2 0.1]);
            
        end
        
        function validate(obj,~,~)
            obj.config = obj.display.config.Value;
            obj.startAt = obj.display.startAt.String;
            obj.nFiles = str2double(obj.display.nFiles.String);
            obj.fileLength = str2double(obj.display.fileLength.String);
            close('Settings')
        end
        
        function immediate(obj,~,~)
            obj.config = obj.display.config.Value;
            obj.startAt = 'now';
            obj.nFiles = str2double(obj.display.nFiles.String);
            obj.fileLength = str2double(obj.display.fileLength.String);
            close('Settings')
        end
      
        
    end
    
end

